### ISSUE TITLE
APL360 is broken

### ISSUE THREAD

**Issue by fuzzballcat** [ktye/ktye.github.io#1]
[The APL360 page](https://ktye.github.io/apl.html) no longer appears to work. Upon startup, a K error message is presented:
```
      A P L \ 3 6 0
       ",y}\'(&~b&same b:{(*x)?NM}'x)^x;x[i]:(#i:&b&same b)#,""}
                             ^
```
Additionally, typing anything into the repl (below, `3`) leads to another error message:
```
      3
 b:{P::P i:&~" "=*'x;x i}                   /blank
                   ^
```

**Comment by ktye** [comment]
thank's for telling. my most important program just broke. i need to fix it.
